"""change sopme column from song table

Revision ID: 5b373dfc6b6b
Revises: f0a807b9a9b1
Create Date: 2022-07-11 17:53:49.215959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b373dfc6b6b'
down_revision = 'f0a807b9a9b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('file_name', sa.String(length=150), nullable=False))
    op.drop_constraint('song_image_key', 'song', type_='unique')
    op.drop_constraint('song_music_type_key', 'song', type_='unique')
    op.drop_constraint('song_song_artist_key', 'song', type_='unique')
    op.drop_constraint('song_song_title_key', 'song', type_='unique')
    op.drop_column('song', 'image')
    op.drop_column('song', 'music_type')
    # ### end Alembic commands ###
    op.execute("COMMIT")

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('music_type', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.add_column('song', sa.Column('image', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.create_unique_constraint('song_song_title_key', 'song', ['song_title'])
    op.create_unique_constraint('song_song_artist_key', 'song', ['song_artist'])
    op.create_unique_constraint('song_music_type_key', 'song', ['music_type'])
    op.create_unique_constraint('song_image_key', 'song', ['image'])
    op.drop_column('song', 'file_name')
    # ### end Alembic commands ###
    op.execute("COMMIT")
