"""create song column

Revision ID: f0a807b9a9b1
Revises: 297ae6845e53
Create Date: 2022-07-11 11:04:57.347495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0a807b9a9b1'
down_revision = '297ae6845e53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_title', sa.String(length=150), nullable=False),
    sa.Column('song_artist', sa.String(length=150), nullable=False),
    sa.Column('music_type', sa.String(length=150), nullable=False),
    sa.Column('image', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image'),
    sa.UniqueConstraint('music_type'),
    sa.UniqueConstraint('song_artist'),
    sa.UniqueConstraint('song_title')
    )
    # ### end Alembic commands ###
    op.execute("COMMIT")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('song')
    # ### end Alembic commands ###
    op.execute("COMMIT")
